openapi: 3.0.3
info:
  title: Koppen API voor landelijke vakantie verhuur
  description: Dit is het koppelstuk tussen mijn amsterdam en landelijke vakantie verhuur
  version: 1.0.0
servers:
  - url: 'https://mijn.amsterdam.nl'
paths:
  /vakantie-verhuur/get:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components'

components:
  schemas:
    vakantie-verhuur-response:
      type: object
      properties:
        status:
          type: string
          example: "OK"
        content:
          type: array
          items:
            type: object
            properties:
              registrationNumber:
                type: string
                example: 'AAAA AAAA AAAA AAAA AAAA'
              city:
                type: string
                example: 'Amsterdam'
              houseLetter:
                type: string
                example: 'a'
              houseNumber:
                type: string
                example: '1',
              houseNumberExtension:
                type: string
                example: '2',
              postalCode:
                type: string
                example: '1012PN'
              shortName:
                type: string
                example: 'Amstel'
              street:
                type: string
                example: 'Amstel'
